traction_ap_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: traction_ap
    joint_speed: 1.17
    motor:
        id: 81
        init: 0
        min: 0
        max: 4095