dual_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: joint1_f
    joint_speed: 0.5
    motor_master:
        id: 12
        init: 633
        min: 307
        max: 1089
    motor_slave:
        id: 22
