dual_joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: joint1_f
    joint_speed: 0.5
    motor_master:
        id: 22
        init: 0
        min: 0
        max: 4095
    motor_slave:
        id: 12
