joint1_f_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: joint1_f
    joint_speed: 0.5
    motor_master:
        id: 12
        init: 2089
        min: 2546
        max: 1590
    motor_slave:
        id: 22

joint2_f_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: joint2_f
    joint_speed: 0.5
    motor_master:
        id: 20
        init: 0
        min: 0
        max: 4095
    motor_slave:
        id: 11
