joint1_f_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: joint1_f
    joint_speed: 0.5
    motor_master:
        id: 11
        init: 633
        min: 307
        max: 1089
    motor_slave:
        id: 12

joint2_f_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: joint2_f
    joint_speed: 0.5
    motor_master:
        id: 21
        init: 1415
        min: 763
        max: 2523
    motor_slave:
        id: 22

joint1_b_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: joint1_b
    joint_speed: 0.5
    motor_master:
        id: 112
        init: 633
        min: 307
        max: 1089
    motor_slave:
        id: 111

joint2_b_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: joint2_b
    joint_speed: 0.5
    motor_master:
        id: 122
        init: 1415
        min: 763
        max: 2523
    motor_slave:
        id: 121
