joint_claw_f1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_f1
    joint_speed: 1.0
    motor:
        id: 31
        init: 0
        min: 0
        max: 4095

joint_claw_f2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_f2
    joint_speed: 1.0
    motor:
        id: 41
        init: 0
        min: 0
        max: 4095

joint_claw_b1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_b1
    joint_speed: 1.0
    motor:
        id: 131
        init: 0
        min: 0
        max: 4095

joint_claw_b2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_b2
    joint_speed: 1.0
    motor:
        id: 141
        init: 0
        min: 0
        max: 4095

joint_claw_ap_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_ap
    joint_speed: 1.0
    motor:
        id: 141
        init: 0
        min: 0
        max: 4095          